# 开发环境配置
server:
  # 服务端口
  port: 8084
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  profiles: dev
  #datasource start
  datasource:
    url: jdbc:mysql://localhost:3306/tags?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #datasource end
  #JPA start
  jpa:
    hibernate:
      ddl-auto: update
      # 无修改命名
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    # 解决JPA懒加载
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  #JPA end
  # 时间戳设置
  jackson:
    date-format: yyyy/MM/dd HH:mm
    time-zone: GMT+8
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java
# netty配置
netty:
  server:
    port: 8087

